/**
 * 「无主 Tab」挂在顶栏下方的详情页页头行：固定高度、内容垂直居中，与全页表单顶栏一致。
 * @see docs/detail-page-layout-reference.md §2
 */
export {
  FORM_PAGE_CHROME_HEADER_HEIGHT_PX as DETAIL_PAGE_NO_TAB_HEADER_HEIGHT_PX,
  FORM_PAGE_HEADER_BACK_TITLE_GAP_PX as DETAIL_PAGE_NO_TAB_HEADER_BACK_TITLE_GAP_PX,
  FORM_PAGE_HEADER_BACK_BUTTON_STYLE as DETAIL_PAGE_HEADER_BACK_BUTTON_STYLE,
  FORM_PAGE_HEADER_TITLE_STYLE as DETAIL_PAGE_HEADER_TITLE_STYLE,
} from './formPageLayout'
